# Generated by Django 2.0.7 on 2018-07-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_category_safaris'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaris',
            name='image',
            field=models.ImageField(default=0, upload_to='Safarimedia/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
